groups:
  - name: catalog-api
    rules:
      - alert: Test
        expr: rate(Test[5m]) > 0
        labels:
          severity: critical
          target: slack
        annotations:
          summary: "Test test"
          description: "An error has occurred when processing"
