@HostAddress = http://localhost:5000

### Send GET request
GET {{HostAddress}}/p/api/products
Accept: application/json

### Send GET request
GET {{HostAddress}}/c/api/carts

### Send POST request with json body
POST https://examples.http-client.intellij.net/post
Content-Type: application/json

{
    "id": 999,
    "value": "content"
}
