trigger: none
pr: none

pool:
  vmImage: ubuntu-latest

stages:
- stage: Install_Mssql
  displayName: Install Mssql Linux
  dependsOn: []
  jobs:
  - job: Install_Postgres
    steps:
    - template: ../install-helm-chart-name.yml
      parameters:
        releaseName: postgres
        chartName: cetic/postgresql
        namespace: infra
        valueFile: k8s/infra/mssql-linux/values.yaml

- stage: Install_Nginx_Ingress
  displayName: Install Nginx ingress controller
  dependsOn: []
  jobs:
  - job : Install_Nginx_Ingress
    steps:
    - template: ../install-helm-chart-name.yml
      parameters:
        releaseName: nginx-ingress
        chartName: stable/nginx-ingress
        namespace: default
        valueFile: k8s/infra/nginx-ingress/values.yaml

- stage: Install_SonarQube
  displayName: Install SonarQube
  dependsOn: []
  jobs:
  - job : Install_SonarQube
    steps:
    - template: ../install-helm-chart-name.yml
      parameters:
        releaseName: sonar
        chartName: oteemocharts/sonarqube
        namespace: infra
        valueFile: k8s/infra/sonarqube/values.yaml