apiVersion: v1
kind: ServiceAccount
metadata:
  name: apiservice
  labels:
    app: apiservice
    app.kubernetes.io/name: apiservice
    app.kubernetes.io/component: api
    app.kubernetes.io/part-of: micro-commerce
automountServiceAccountToken: false
