resources:
- deployment.yml
- service.yml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
- name: redis-env
  literals:
    - OTEL_EXPORTER_OTLP_ENDPOINT=http://aspire-dashboard:4317
    - OTEL_SERVICE_NAME=redis

