apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: bitnami
  namespace: flux-system
spec:
  interval: 1h
  type: oci
  url: oci://registry-1.docker.io/bitnamicharts
# ---
# apiVersion: helm.toolkit.fluxcd.io/v2beta2
# kind: HelmRelease
# metadata:
#   name: redis
#   namespace: dev
# spec:
#   interval: 5m
#   chart:
#     spec:
#       chart: redis
#       sourceRef:
#         kind: HelmRepository
#         name: bitnami
#         namespace: flux-system
#   values:
#     auth:
#       enabled: false
#     master:
#       resources:
#         requests:
#           cpu: 50m
#           memory: 100Mi
#         limits:
#           cpu: 150m
#           memory: 250Mi
#       persistence:
#         size: 4Gi
#       disableCommands: []
#     replica:
#       persistence:
#         size: 4Gi
#       replicaCount: 0
# ---
# apiVersion: helm.toolkit.fluxcd.io/v2beta2
# kind: HelmRelease
# metadata:
#   name: rabbitmq
#   namespace: dev
# spec:
#   interval: 5m
#   chart:
#     spec:
#       chart: rabbitmq
#       sourceRef:
#         kind: HelmRepository
#         name: bitnami
#         namespace: flux-system
#   values:
#     replicaCount: 1
#     auth:
#       username: guest
#       password: guest