apiVersion: v1
kind: Service
metadata:
  name: {{ include "catalog-api.fullname" . }}
  labels:
    {{- include "catalog-api.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port.http }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.service.port.grpc }}
      targetPort: grpc
      protocol: TCP
      name: grpc
  selector:
    {{- include "catalog-api.selectorLabels" . | nindent 4 }}
