trigger:
  branches:
    include:
      - master
      - feature/*
    exclude:
      - ref/tags/*
  paths:
    include:
      - src
      - tests

pool:
  vmImage: 'ubuntu-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

stages:
- stage: build_and_run_tests
  jobs:
    - job: build
      displayName: Build
      steps:
        - task: DotNetCoreCLI@2
          displayName: Restore
          inputs:
            command: 'restore'
            projects: '$(solution)'

        - task: DotNetCoreCLI@2
          displayName: Build
          inputs:
            command: 'build'
            projects: '$(solution)'
            arguments: '--no-restore'

    - job: run_tests
      displayName: Run tests
      steps:
        - task: DotNetCoreCLI@2
          displayName: Test
          inputs:
            command: 'test'
            projects: '$(solution)'
            arguments: '/p:CollectCoverage=true'
            nobuild: true
            publishTestResults: true
