name: Build and run unit tests
description: Build and run unit tests

inputs:
  project-path:
    required: true
    description: "Project path"

runs:
  using: composite
  steps:
    - name: Install dependencies
      working-directory: ${{inputs.project-path}}
      shell: bash
      run: dotnet restore

    - name: Build
      working-directory: ${{inputs.project-path}}
      shell: bash
      run: dotnet build -c Release --no-restore

    - name: Run Tests
      working-directory: ${{inputs.project-path}}.Tests
      shell: bash
      run: dotnet test -c Release /p:CollectCoverage=true
