apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
  labels:
    app: gateway
    app.kubernetes.io/name: gateway
    app.kubernetes.io/component: gateway
    app.kubernetes.io/part-of: micro-commerce
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
      app.kubernetes.io/name: gateway
      app.kubernetes.io/component: gateway
      app.kubernetes.io/part-of: micro-commerce
  template:
    metadata:
      labels:
        app: gateway
        app.kubernetes.io/name: gateway
        app.kubernetes.io/component: gateway
        app.kubernetes.io/part-of: micro-commerce
    spec:
      serviceAccountName: gateway
      containers:
      - name: gateway
        securityContext:
          runAsNonRoot: true
          readOnlyRootFilesystem: true
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
        image: gateway:dev
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: Production
        - name: ReverseProxy__Clusters__apiservice__Destinations__default__Address
          value: "http://apiservice:8080"
        - name: ConnectionStrings__keycloak
          value: "http://keycloak.micro-commerce.svc.cluster.local:8080"
        - name: Cors__Origins__0
          value: "http://localhost:38800"
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: "http://otel-collector:4317"
        - name: OTEL_SERVICE_NAME
          value: "gateway"
        livenessProbe:
          httpGet:
            path: /alive
            port: 8080
          periodSeconds: 15
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          periodSeconds: 10
        resources:
          requests:
            memory: 128Mi
            cpu: 100m
          limits:
            memory: 256Mi
            cpu: 250m
