apiVersion: v1
kind: ServiceAccount
metadata:
  name: gateway
  labels:
    app: gateway
    app.kubernetes.io/name: gateway
    app.kubernetes.io/component: gateway
    app.kubernetes.io/part-of: micro-commerce
automountServiceAccountToken: false
