apiVersion: v1
kind: Service
metadata:
  name: gateway
  labels:
    app: gateway
    app.kubernetes.io/name: gateway
    app.kubernetes.io/component: gateway
    app.kubernetes.io/part-of: micro-commerce
spec:
  selector:
    app: gateway
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: gateway-nodeport
  labels:
    app: gateway
    app.kubernetes.io/name: gateway
    app.kubernetes.io/component: gateway
    app.kubernetes.io/part-of: micro-commerce
spec:
  type: NodePort
  selector:
    app: gateway
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30800
    protocol: TCP
