# Default values for catalog-api.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# helm package .
# helm lint -f ./values.yaml .
# helm upgrade catalog-api --install -f ./values.yaml --namespace=b-shop .

replicaCount: 1

image:
  repository: bshopacr.azurecr.io/catalog-api
  tag: latest
  pullPolicy: IfNotPresent

imagePullSecrets:
- name: acr-secret
nameOverride: catalog-api
fullnameOverride: catalog-api

env:
  ASPNETCORE_ENVIRONMENT: Production
  ASPNETCORE_URLS: http://0.0.0.0:80
  ConnectionStrings__DefaultConnection: Server=mssql-mssql-linux,1433;Database=catalog-api;User Id=sa;Password=P@ssw0rd;

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths: []
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources:
  limits:
    cpu: 100m
    memory: 256Mi
  requests:
    cpu: 50m
    memory: 128Mi

probes:
  liveness:
    path: /health
    initialDelaySeconds: 15
    periodSeconds: 30
  readiness:
    path: /health
    initialDelaySeconds: 30
    periodSeconds: 60
    timeoutSeconds: 5

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
