podTemplate(containers: [
    containerTemplate(name: 'netcore31', image: 'mcr.microsoft.com/dotnet/core/sdk:3.1', ttyEnabled: true)
  ]) {

    node(POD_LABEL) {
        stage('Build') {
            container('netcore31') {
                stage('Restore') {
                    sh 'dotnet restore'
                }
            }
        }
    }
}