code-analysis-identity-api:
  stage: code-analysis
  image: mcr.microsoft.com/dotnet/core/sdk:3.1
  variables:
    SERVICE_NAME: Identity.API
  before_script:
    - dotnet --info
  script:
    - cd src/${SERVICE_NAME}
    - dotnet restore
    - dotnet build --no-restore -c Release
    - cd ${CI_PROJECT_DIR}
    - cd tests/${SERVICE_NAME}
    - dotnet test ${SERVICE_NAME}.FunctionalTests --no-build -c Release /p:CollectCoverage=true
    - dotnet test ${SERVICE_NAME}.UnitTests --no-build -c Release /p:CollectCoverage=true
