GET {{baseUrl}}
###
POST {{baseUrl}}/login
Content-Type: application/json

{
  "email": "bao2703@gmail.com",
  "password": "Bao@2703"
}
###
POST {{baseUrl}}/api/products
Content-Type: application/json

{
  "name": "Apple"
}
###
GET {{baseUrl}}/api/products/69d734fb-e982-4bde-8410-7e04d3718de1
###
GET {{baseUrl}}/api/carts
Authorization: Bearer {{token}}
###
