apiVersion: apps/v1
kind: Deployment
metadata:
  name: azurite
spec:
  replicas: 1
  selector: { matchLabels: { app: azurite } }
  template:
    metadata: { labels: { app: azurite } }
    spec:
      containers:
        - name: azurite
          image: mcr.microsoft.com/azure-storage/azurite:latest
          args: ["azurite-blob", "--blobHost", "0.0.0.0", "--blobPort", "10000",
                 "--disableProductStyleUrl", "--location", "/data", "--skipApiVersionCheck"]
          ports: [ { containerPort: 10000 } ]
          volumeMounts:
            - { name: data, mountPath: /data }
      volumes:
        - name: data
          persistentVolumeClaim: { claimName: azurite-data }
