apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: micro-commerce-root
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: micro-commerce
  source:
    repoURL: https://github.com/baotoq/micro-commerce.git
    targetRevision: master
    path: infra/k8s/argocd/apps
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
