apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: micro-commerce-root
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/baotoq/micro-commerce.git
    targetRevision: master
    path: infra/k8s/argocd/apps
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
