// <auto-generated />
using System;
using MicroCommerce.ApiService.Features.Inventory.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MicroCommerce.ApiService.Features.Inventory.Infrastructure.Migrations
{
    [DbContext(typeof(InventoryDbContext))]
    [Migration("20260224102036_ConventionsDryConfiguration")]
    partial class ConventionsDryConfiguration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("inventory")
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MicroCommerce.ApiService.Features.Inventory.Domain.Entities.StockAdjustment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AdjustedBy")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("adjusted_by");

                    b.Property<int>("Adjustment")
                        .HasColumnType("integer")
                        .HasColumnName("adjustment");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("QuantityAfter")
                        .HasColumnType("integer")
                        .HasColumnName("quantity_after");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("reason");

                    b.Property<Guid>("StockItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("stock_item_id");

                    b.HasKey("Id")
                        .HasName("pk_stock_adjustments");

                    b.HasIndex("CreatedAt")
                        .IsDescending()
                        .HasDatabaseName("ix_stock_adjustments_created_at");

                    b.HasIndex("StockItemId")
                        .HasDatabaseName("ix_stock_adjustments_stock_item_id");

                    b.ToTable("stock_adjustments", "inventory");
                });

            modelBuilder.Entity("MicroCommerce.ApiService.Features.Inventory.Domain.Entities.StockItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<int>("QuantityOnHand")
                        .HasColumnType("integer")
                        .HasColumnName("quantity_on_hand");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_stock_items");

                    b.HasIndex("ProductId")
                        .IsUnique()
                        .HasDatabaseName("ix_stock_items_product_id");

                    b.ToTable("stock_items", "inventory");
                });

            modelBuilder.Entity("MicroCommerce.ApiService.Features.Inventory.Domain.Entities.StockReservation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<Guid>("StockItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("stock_item_id");

                    b.HasKey("Id")
                        .HasName("pk_stock_reservations");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("ix_stock_reservations_expires_at");

                    b.HasIndex("StockItemId")
                        .HasDatabaseName("ix_stock_reservations_stock_item_id");

                    b.ToTable("stock_reservations", "inventory");
                });

            modelBuilder.Entity("MicroCommerce.ApiService.Features.Inventory.Domain.Entities.StockReservation", b =>
                {
                    b.HasOne("MicroCommerce.ApiService.Features.Inventory.Domain.Entities.StockItem", null)
                        .WithMany("Reservations")
                        .HasForeignKey("StockItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_stock_reservations_stock_items_stock_item_id");
                });

            modelBuilder.Entity("MicroCommerce.ApiService.Features.Inventory.Domain.Entities.StockItem", b =>
                {
                    b.Navigation("Reservations");
                });
#pragma warning restore 612, 618
        }
    }
}
