trigger:
  branches:
    include:
    - master
    exclude:
    - ref/tags/*
  paths:
    include:
    - src/Catalog.API
    - tests/**/Catalog.API**
    - pipeline/k8s/catalog-api
    - pipeline/azure/catalog-api

pool:
  vmImage: ubuntu-latest

variables:
- template: ../variables.yml

stages:
- stage: Build_and_Run_Tests
  jobs:
  - job: Build
    displayName: Build
    steps:
    - template: ../build-test-sonar-scan.yml
      parameters:
        projectName: catalog-api
        projectPath: Catalog.API

- stage: Build_and_Push_Image
  displayName: Build and push docker image
  jobs:
  - job: Build_and_Push_Image
    displayName: Build and push docker image
    steps:
    - template: ../compose.yml
      parameters:
        action: build
        services: [catalog-api]
    - template: ../compose.yml
      parameters:
        action: push
        services: [catalog-api]

- stage: Deploy_Helm_Chart
  displayName: Deploy helm chart
  jobs:
  - job: Deploy_Helm_Chart
    displayName: Deploy helm chart
    steps:
    - template: ../package-helm-chart.yml
      parameters:
        service: catalog-api

    - template: ../install-helm-chart.yml
      parameters:
        service: catalog-api
        namespace: bshop
