# Default values for react-web.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# helm package .
# helm lint -f ./values.yaml .
# helm upgrade react-web --install -f ./values.yaml --namespace=bshop .

replicaCount: 1

image:
  repository: react-web
  tag: latest
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: react-web
fullnameOverride: react-web

env:
  ASPNETCORE_ENVIRONMENT: Production
  ASPNETCORE_URLS: http://0.0.0.0:80
  Kestrel__Endpoints__Http__Url: http://0.0.0.0:80
  PathBase: /react

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  annotations:
    kubernetes.io/ingress.class: nginx
  hosts:
    - host: k8s.local.com
      paths: ["/react"]

resources:
  limits:
    cpu: 100m
    memory: 256Mi
  requests:
    cpu: 50m
    memory: 128Mi

probes:
  liveness:
    path: /health/liveness
    initialDelaySeconds: 15
    periodSeconds: 30
  readiness:
    path: /health/readiness
    initialDelaySeconds: 30
    periodSeconds: 60
    timeoutSeconds: 5

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
