route:
  group_by: ["target", "severity"]
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 4h
  receiver: slack-general
  routes:
    - match:
        target: slack
      receiver: slack-general
receivers:
  - name: slack-general
    slack_configs:
      - api_url: "http://localhost:123"
        channel: '#general'
        text: "{{ range .Alerts }}Summary: {{ .Annotations.summary }}\nDescription: {{ .Annotations.description }}\n{{ end }}"
        send_resolved: true
