global:
  scrape_interval: 30s
  scrape_timeout: 10s
  evaluation_interval: 30s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alertmanager:9093

rule_files:
  - alert-rules.yml

scrape_configs:
  - job_name: basket-api
    static_configs:
      - targets: ["basket-api"]
  - job_name: catalog-api
    static_configs:
      - targets: ["catalog-api"]
  - job_name: ordering-api
    static_configs:
      - targets: ["ordering-api"]
  - job_name: identity-api
    static_configs:
      - targets: ["identity-api"]
