<Project Sdk="Aspire.AppHost.Sdk/13.3.3">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UserSecretsId>99355ead-cdca-4b8e-95ca-24aa2bf9d882</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.JavaScript" Version="13.3.3" />
    <PackageReference Include="Aspire.Hosting.PostgreSQL" Version="13.3.3" />
    <PackageReference Include="Aspire.Hosting.Redis" Version="13.3.3" />
    <PackageReference Include="CommunityToolkit.Aspire.Hosting.Dapr" Version="13.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Services\Catalog.API\src\Api\MicroCommerce.Catalog.csproj" />
  </ItemGroup>
</Project>
