apiVersion: v1
kind: ConfigMap
metadata:
  name: catalog-config
data:
  ASPNETCORE_ENVIRONMENT: "Development"
  SEED_PRODUCTS: "true"
  ConnectionStrings__cache: "redis:6379"
  Keycloak__Authority: "http://keycloak.micro-commerce.k8s.orb.local/realms/microcommerce"
