apiVersion: v1
kind: Secret
metadata:
  name: catalog-secrets
type: Opaque
stringData:
  ConnectionStrings__catalogdb: "Host=postgres;Port=5432;Database=catalogdb;Username=postgres;Password=dev-only-postgres-pw"
  ConnectionStrings__photos: "DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=http://azurite.micro-commerce.k8s.orb.local/devstoreaccount1;"
