trigger:
  branches:
    include:
      - master
    exclude:
      - ref/tags/*
  paths:
    include:
      - src/Webs/MicroCommerce.React.Web
      - deploy/k8s/react-web
      - pipeline/azure/react-web
pr: none

pool:
  vmImage: ubuntu-latest

parameters:
  - name: runTest
    displayName: Run test?
    type: boolean
    default: false

stages:
  - stage: Build_and_Run_Tests
    displayName: Build and Run tests
    jobs:
      - job: Build
        displayName: Build
        steps:
          - task: NodeTool@0
            inputs:
              versionSpec: 13.x
            displayName: Install Node.js

          - script: yarn
            displayName: Install dependencies

          - ${{ if eq(parameters.runTest, true) }}:
              - script: yarn test
                displayName: Run unit tests

          - script: yarn build
            displayName: Run build

          - task: PublishBuildArtifacts@1
            displayName: Publish Artifact
            inputs:
              pathtoPublish: build
