parameters:
  action:
  services: []
  registryEndpoint: 'bshopacr'

steps:
- ${{ each service in parameters.services }}:
  - task: DockerCompose@0
    displayName: Docker Compose ${{ parameters.action }} ${{ service }}
    inputs:
      dockerComposeCommand: ${{ parameters.action }} ${{ service }}
      dockerComposeFile: pipeline/docker-compose/docker-compose-ci.yaml
      currentWorkingDirectory: $(Build.SourcesDirectory)/pipeline/docker-compose
      projectName: $(Build.Repository.Name)
      containerRegistryType: Container Registry
      dockerRegistryEndpoint: ${{ parameters.registryEndpoint }}
      includeLatestTag: true
      qualifyImageNames: true
