# helm repo add oteemocharts https://oteemo.github.io/charts
# helm upgrade sonar oteemocharts/sonarqube --install -f ./values.yaml -f values.local.yml --namespace=infra

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
  hosts:
    - name: localhost
      path: /sonar