using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace MicroCommerce.ApiService.Features.Catalog.Infrastructure.Migrations
{
    /// <inheritdoc />
    public partial class MoveOutboxToBaseContext : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            // Outbox tables now owned by BaseDbContext (shared across all feature DbContexts).
            // Tables may already exist from legacy OutboxDbContext — use IF NOT EXISTS for idempotency.
            migrationBuilder.Sql("""
                CREATE SCHEMA IF NOT EXISTS outbox;

                CREATE TABLE IF NOT EXISTS outbox.inbox_state (
                    id bigint GENERATED BY DEFAULT AS IDENTITY,
                    message_id uuid NOT NULL,
                    consumer_id uuid NOT NULL,
                    lock_id uuid NOT NULL,
                    row_version bytea,
                    received timestamp with time zone NOT NULL,
                    receive_count integer NOT NULL DEFAULT 0,
                    expiration_time timestamp with time zone,
                    consumed timestamp with time zone,
                    delivered timestamp with time zone,
                    last_sequence_number bigint,
                    CONSTRAINT pk_inbox_state PRIMARY KEY (id),
                    CONSTRAINT ak_inbox_state_message_id_consumer_id UNIQUE (message_id, consumer_id)
                );

                CREATE TABLE IF NOT EXISTS outbox.outbox_state (
                    outbox_id uuid NOT NULL,
                    lock_id uuid NOT NULL,
                    row_version bytea,
                    created timestamp with time zone NOT NULL,
                    delivered timestamp with time zone,
                    last_sequence_number bigint,
                    CONSTRAINT pk_outbox_state PRIMARY KEY (outbox_id)
                );

                CREATE TABLE IF NOT EXISTS outbox.outbox_message (
                    sequence_number bigint GENERATED BY DEFAULT AS IDENTITY,
                    enqueue_time timestamp with time zone,
                    sent_time timestamp with time zone NOT NULL,
                    headers text,
                    properties text,
                    inbox_message_id uuid,
                    inbox_consumer_id uuid,
                    outbox_id uuid,
                    message_id uuid NOT NULL,
                    content_type character varying(256) NOT NULL,
                    message_type text NOT NULL,
                    body text NOT NULL,
                    conversation_id uuid,
                    correlation_id uuid,
                    initiator_id uuid,
                    request_id uuid,
                    source_address character varying(256),
                    destination_address character varying(256),
                    response_address character varying(256),
                    fault_address character varying(256),
                    expiration_time timestamp with time zone,
                    CONSTRAINT pk_outbox_message PRIMARY KEY (sequence_number),
                    CONSTRAINT fk_outbox_message_inbox_state_inbox_message_id_inbox_consumer_ FOREIGN KEY (inbox_message_id, inbox_consumer_id)
                        REFERENCES outbox.inbox_state (message_id, consumer_id),
                    CONSTRAINT fk_outbox_message_outbox_state_outbox_id FOREIGN KEY (outbox_id)
                        REFERENCES outbox.outbox_state (outbox_id)
                );

                CREATE INDEX IF NOT EXISTS ix_inbox_state_delivered ON outbox.inbox_state (delivered);
                CREATE INDEX IF NOT EXISTS ix_outbox_message_enqueue_time ON outbox.outbox_message (enqueue_time);
                CREATE INDEX IF NOT EXISTS ix_outbox_message_expiration_time ON outbox.outbox_message (expiration_time);
                CREATE UNIQUE INDEX IF NOT EXISTS ix_outbox_message_inbox_message_id_inbox_consumer_id_sequence_ ON outbox.outbox_message (inbox_message_id, inbox_consumer_id, sequence_number);
                CREATE UNIQUE INDEX IF NOT EXISTS ix_outbox_message_outbox_id_sequence_number ON outbox.outbox_message (outbox_id, sequence_number);
                CREATE INDEX IF NOT EXISTS ix_outbox_state_created ON outbox.outbox_state (created);
                """);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("""
                DROP TABLE IF EXISTS outbox.outbox_message;
                DROP TABLE IF EXISTS outbox.inbox_state;
                DROP TABLE IF EXISTS outbox.outbox_state;
                DROP SCHEMA IF EXISTS outbox;
                """);
        }
    }
}
