apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: argocd-server
  namespace: argocd
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`micro-commerce.store`)
      services:
        - name: argocd-server
          port: http
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: argocd-server2
  namespace: argocd
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`argocd.micro-commerce.store`)
      services:
        - name: argocd-server
          port: http
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: my-cluster-issuer
  namespace: kube-system
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: bao2703@gmail.com
    privateKeySecretRef:
      name: letsencrypt-dev
    solvers:
      - http01:
          ingress:
            class: traefik
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: my-cert
  namespace: kube-system
spec:
  secretName: my-cert
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  issuerRef:
    name: my-cluster-issuer
    kind: ClusterIssuer
  commonName: "micro-commerce.store"
  dnsNames:
    - "micro-commerce.store"