name: Run dotnet restore and build
description: Run dotnet restore and build

inputs:
  project-path:
    required: true
    description: Project path
  configuration:
    required: false
    default: Release
    description: Build configuration

runs:
  using: composite
  steps:
    - name: Install dependencies
      working-directory: ${{inputs.project-path}}
      shell: bash
      run: dotnet restore

    - name: Build
      working-directory: ${{inputs.project-path}}
      shell: bash
      run: dotnet build -c ${{inputs.configuration}} --no-restore
