name: Restore and build dotnet
description: Restore and build dotnet

inputs:
  project-path:
    required: true
    description: "Project path"

runs:
  using: composite
  steps:
    - name: Install dependencies
      working-directory: ${{inputs.project-path}}
      shell: bash
      run: dotnet restore

    - name: Build
      working-directory: ${{inputs.project-path}}
      shell: bash
      run: dotnet build -c Release --no-restore
