trigger:
  branches:
    include:
    - master
    exclude:
    - ref/tags/*
  paths:
    include:
    - src/Services/Identity
    - deploy/k8s/identity-api
    - pipeline/azure/identity-api
pr: none

parameters:
- name: deploy
  displayName: Deploy?
  type: boolean
  default: false

pool:
  vmImage: ubuntu-latest

stages:
- stage: Build_and_Run_Tests
  displayName: Build and Run tests
  jobs:
  - job: Build
    displayName: Build
    steps:
    - template: ../build-test-sonar-scan.yml
      parameters:
        projectKey: identity-api
        projectPath: Services/Identity/MicroCommerce.Identity.API

- ${{ if eq(parameters.deploy, true) }}:
  - stage: Build_and_Push_Image
    displayName: Build and push docker image
    jobs:
    - job: Build_and_Push_Image
      displayName: Build and push docker image
      steps:
      - template: ../compose.yml
        parameters:
          action: build
          services: [identity-api]
      - template: ../compose.yml
        parameters:
          action: push
          services: [identity-api]

  - stage: Deploy
    displayName: Deploy
    dependsOn:
    - Build_and_Run_Tests
    - Build_and_Push_Image
    condition: and(succeeded(), or(eq(variables['Build.SourceBranch'], 'refs/heads/master'), eq(variables['isDeploy'], 'true')))
    jobs:
    - deployment: app
      displayName: App deployment
      environment: dev
      strategy:
        runOnce:
          deploy:
            steps:
            - template: ../package-helm-chart.yml
              parameters:
                service: identity-api

            - template: ../install-helm-chart.yml
              parameters:
                service: identity-api
                namespace: bshop
                valueFile: k8s/identity-api/values.yaml
                arguments: -f k8s/identity-api/values.azure.yaml
