image:
  repository: bshopacr.azurecr.io/react-web
  tag: latest

env:
  PATH_BASE:

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: true
  hosts:
    - host: bshop.dongnai-vn.com
      paths: ["/"]
  tls:
    - hosts:
        - bshop.dongnai-vn.com
      secretName: react-tls