# helm upgrade react-web --install -f ./values.yaml -f values.local.yml --namespace=bshop .

image:
  repository: react-web
  tag: latest

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
  hosts:
    - host: localhost
      paths: ["/react"]