{{- if .Values.virtualService.enabled -}}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ include "catalog-api.fullname" . }}-http
  namespace: {{ .Release.Namespace }}
spec:
  hosts:
  - {{ .Values.virtualService.gateway.host }}
  gateways:
  - {{ .Values.virtualService.gateway.name }}
  http:
  - match:
    - uri:
        prefix: {{ .Values.env.PathBase }}
    route:
    - destination:
        host: {{ include "catalog-api.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local
        port:
          number: {{ .Values.service.port.http }}
{{- end }}
---
{{- if .Values.virtualService.enabled -}}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ include "catalog-api.fullname" . }}-grpc
  namespace: {{ .Release.Namespace }}
spec:
  hosts:
  - {{ .Values.virtualService.gateway.host }}
  gateways:
  - {{ .Values.virtualService.gateway.name }}
  http:
  - match:
    - headers:
        grpc-location:
          prefix: {{ include "catalog-api.fullname" . }}
    route:
    - destination:
        host: {{ include "catalog-api.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local
        port:
          number: {{ .Values.service.port.grpc }}
{{- end }}