version: '3.4'

services:
  redis:
    image: redis:alpine
    volumes:
      - redis-data:/data
    restart: always
    networks:
      - backend

  postgres:
    image: postgres:latest
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: always
    networks:
      - backend

  zipkin:
    image: openzipkin/zipkin:latest
    restart: always
    networks:
      - backend

  seq:
    image: datalust/seq
    volumes:
      - seq-data:/data
    environment:
      - ACCEPT_EULA=Y
    restart: always
    networks:
      - backend

  basket-api:
    image: ${DOCKER_REGISTRY-}microcommerce-basket-api
    build:
      context: .
      dockerfile: Services/Basket/MicroCommerce.Basket.API/Dockerfile
    restart: always
    networks:
      - backend

  catalog-api:
    image: ${DOCKER_REGISTRY-}microcommerce-catalog-api
    build:
      context: .
      dockerfile: Services/Catalog/MicroCommerce.Catalog.API/Dockerfile
    restart: always
    networks:
      - backend

  ordering-api:
    image: ${DOCKER_REGISTRY-}microcommerce-ordering-api
    build:
      context: .
      dockerfile: Services/Ordering/MicroCommerce.Ordering.API/Dockerfile
    restart: always
    networks:
      - backend

  identity-api:
    image: ${DOCKER_REGISTRY-}microcommerce-identity-api
    build:
      context: .
      dockerfile: Services/Identity/MicroCommerce.Identity.API/Dockerfile
    restart: always
    networks:
      - backend

volumes:
  postgres-data:
  redis-data:
  seq-data:

networks:
  frontend:
  backend: