<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="MediatR" Version="12.5.0" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\MicroCommerce.Domain\MicroCommerce.Domain.csproj" />
    <ProjectReference Include="..\MicroCommerce.Infrastructure\MicroCommerce.Infrastructure.csproj" />
  </ItemGroup>
</Project>
