services:
  
  db:
    container_name: "db"
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5431:5432"
  
  redis:
    container_name: "redis"
    image: "redis:latest"
    ports:
      - "6371:6379"
  
  rabbitmq:
    container_name: "rabbitmq"
    image: rabbitmq:3-management-alpine
    ports:
      - 5670:5672
      - 15670:15672
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
  
  cart-service:
    container_name: "cart-service"
    image: cart-service
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SERVICE_NAME: CartService
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=db;Port=5432;Database=micro-commerce;User Id=admin;Password=admin;
    ports:
      - "50011:80"

  product-service:
    container_name: "product-service"
    image: product-service
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SERVICE_NAME: CartService
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=db;Port=5432;Database=micro-commerce;User Id=admin;Password=admin;
    ports:
      - "50021:80"

