apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: micro-commerce

resources:
- postgres/
- rabbitmq/
- keycloak/
- otel-collector/
- aspire-dashboard/
- apiservice/
- gateway/
- web/
