apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: micro-commerce

resources:
- ../../base/postgres
- ../../base/rabbitmq
- ../../base/keycloak
- ../../base/otel-collector
- ../../base/aspire-dashboard
- apiservice/
- gateway/
- web/
