apiVersion: v1
kind: Service
metadata:
  name: keycloak
  namespace: micro-commerce
spec:
  selector:
    app: keycloak
  ports:
  - port: 8080
    targetPort: 8080
    name: http
---
apiVersion: v1
kind: Service
metadata:
  name: keycloak-nodeport
  namespace: micro-commerce
spec:
  type: NodePort
  selector:
    app: keycloak
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30080
    name: http
