apiVersion: v1
kind: ServiceAccount
metadata:
  name: keycloak
  labels:
    app: keycloak
    app.kubernetes.io/name: keycloak
    app.kubernetes.io/component: auth
    app.kubernetes.io/part-of: micro-commerce
automountServiceAccountToken: false
