---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: messaging
  labels:
    app: messaging
spec:
  serviceName: "messaging"
  replicas: 1
  selector:
    matchLabels:
      app: messaging
  template:
    metadata:
      labels:
        app: messaging
    spec:
      containers:
        - name: messaging
          image: docker.io/library/rabbitmq:3-management
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5672
            - containerPort: 15672
          envFrom:
            - configMapRef:
                name: messaging-env
          volumeMounts:
            - name: microcommerce-apphost-messaging-data
              mountPath: /var/lib/rabbitmq
  volumeClaimTemplates:
    - metadata:
        name: microcommerce-apphost-messaging-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
