apiVersion: v1
kind: Service
metadata:
  name: otel-collector
  labels:
    app: otel-collector
    app.kubernetes.io/name: otel-collector
    app.kubernetes.io/component: observability
    app.kubernetes.io/part-of: micro-commerce
spec:
  selector:
    app: otel-collector
  ports:
  - port: 4317
    targetPort: 4317
    name: otlp-grpc
    protocol: TCP
  - port: 4318
    targetPort: 4318
    name: otlp-http
    protocol: TCP
