apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infra
  namespace: argocd
  annotations: { argocd.argoproj.io/sync-wave: "0" }
  finalizers: [ resources-finalizer.argocd.argoproj.io ]
spec:
  project: default
  source:
    repoURL: https://github.com/baotoq/micro-commerce.git
    path: deploy/k8s/infra
    targetRevision: gitops
  destination:
    server: https://kubernetes.default.svc
    namespace: micro-commerce
  syncPolicy:
    automated: { prune: true, selfHeal: true }
    syncOptions: [ CreateNamespace=true ]
