apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: micro-commerce
  namespace: fluxcd-production
spec:
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  path: ./deploy/apps/prod
  prune: true
  wait: true
  timeout: 5m0s
