version: '3.8'

services:
  nginx-proxy:
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    restart: on-failure

  redis:
    command: ["redis-server", "--appendonly", "yes", "--requirepass", "P@ssw0rd"]
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - redis-data:/data

  postgres:
    environment:
      - POSTGRES_MULTIPLE_DATABASES=catalog,identity
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=P@ssw0rd
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./create-database.sh:/docker-entrypoint-initdb.d/create-database.sh
    ports:
      - "${POSTGRES_PORT}:5432"

  flyway:
    entrypoint: []
    command:
      - bash
      - -c
      - |
        flyway -url=jdbc:postgresql://postgres:5432/catalog -locations=filesystem:/sql/catalog migrate
        flyway -url=jdbc:postgresql://postgres:5432/identity -locations=filesystem:/sql/identity migrate
    environment:
      - FLYWAY_USER=postgres
      - FLYWAY_PASSWORD=P@ssw0rd
      - FLYWAY_CONNECT_RETRIES=15
    volumes:
      - ./Services/Catalog/MicroCommerce.Catalog.API/Migrations/scripts:/sql/catalog
      - ./Services/Identity/MicroCommerce.Identity.API/Migrations/scripts:/sql/identity

  zipkin:
    environment:
      - VIRTUAL_HOST=local.zipkin.com
    ports:
      - "${ZIPKIN_PORT}:9411"

  seq:
    environment:
      - VIRTUAL_HOST=local.seq.com
      - ACCEPT_EULA=Y
    volumes:
      - seq-data:/data

  prometheus:
    environment:
      - VIRTUAL_HOST=local.prometheus.com
    ports:
      - "${PROMETHEUS_PORT}:9090"
    volumes:
      - ./monitoring:/etc/prometheus
      - prometheus-data:/prometheus

  grafana:
    environment:
      - VIRTUAL_HOST=local.grafana.com
      - GF_SECURITY_ADMIN_PASSWORD=P@ssw0rd
      - PROMETHEUS_URL=http://prometheus:9090
      - DASHBOARDS_BACKUP_FOLDER=/var/lib/grafana/dashboards
    ports:
      - "${GRAFANA_PORT}:3000"
    volumes:
      - ./monitoring/grafana/provisioning:/etc/grafana/provisioning
      - ./monitoring/grafana/dashboard-backup:/var/lib/grafana/dashboards

  alertmanager:
    environment:
      - VIRTUAL_HOST=local.alertmanager.com
    ports:
      - "${ALERTMANAGER_PORT}:9093"
    volumes:
      - ./monitoring:/etc/alertmanager
      - alertmanager-data:/alertmanager

  mail:
    ports:
      - "37408:37408"
      - "25:25"

  basket-api:
    environment:
      - VIRTUAL_HOST=local.basket-api.com
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro

  catalog-api:
    environment:
      - VIRTUAL_HOST=local.catalog-api.com
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro

  ordering-api:
    environment:
      - VIRTUAL_HOST=local.ordering-api.com
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro

  identity-api:
    environment:
      - VIRTUAL_HOST=local.identity-api.com
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80;https://0.0.0.0:443
    ports:
      - "${IDENTITY_API_HTTPS_PORT}:443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      #- ./certs:/root/.aspnet/https:ro

  gateway-api:
    environment:
      - VIRTUAL_HOST=local.gateway-api.com
      - ASPNETCORE_ENVIRONMENT=Dapr
      - ASPNETCORE_URLS=http://0.0.0.0:80
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      #- ./certs:/root/.aspnet/https:ro

  healthchecks-web:
    environment:
      - VIRTUAL_HOST=local.healthchecks-web.com
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80

volumes:
  postgres-data:
  redis-data:
  seq-data:
  alertmanager-data:
  prometheus-data:
