name: micro-commerce
extensions:
  - name: dapr
    log-level: debug
    config: ./dapr/config.yaml
    components-path: "./dapr/components"
    exclude-placement-container: true
    placement-port: 50005

services:
  - name: postgres
    image: postgres
    env:
      - name: POSTGRES_PASSWORD
        value: P@ssw0rd
    bindings:
      - port: 15432
        connectionString: Server=${host};Port=${port};User Id=postgres;Password=${env:POSTGRES_PASSWORD};

  - name: redis
    image: redis
    bindings:
      - port: 16379

  - name: ocelot-gateway
    project: Gateways/OcelotGateway.API/OcelotGateway.API.csproj
    env:
      - name: ASPNETCORE_ENVIRONMENT
        value: Dapr
    bindings:
      - port: 16000

  - name: catalog-api
    project: Services/Catalog/MicroCommerce.Catalog.API/MicroCommerce.Catalog.API.csproj
    env:
      - name: ConnectionStrings__DefaultConnection
        value: Server=localhost;Port=15432;Database=postgres;User Id=postgres;Password=P@ssw0rd;
    bindings:
      - port: 16001

  - name: ordering-api
    project: Services/Ordering/MicroCommerce.Ordering.API/MicroCommerce.Ordering.API.csproj
    env:
      - name: ConnectionStrings__DefaultConnection
        value: Server=localhost;Port=15432;Database=postgres;User Id=postgres;Password=P@ssw0rd;
    bindings:
      - port: 16002
