image:
  repository: bshopacr.azurecr.io/identity-api
  tag: latest

env:
  PATH_BASE:
  Client__Swagger__Uri: https://api.dongnai-vn.com
  Client__React__Uri: https://bshop.dongnai-vn.com

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: true
  hosts:
    - host: idm.dongnai-vn.com
      paths: ["/"]
  tls:
    - secretName: identity-tls
      hosts:
        - idm.dongnai-vn.com