# helm upgrade identity-api --install -f ./values.yaml -f values.local.yml --namespace=bshop .

image:
  repository: identity-api
  tag: latest

imagePullSecrets: []

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
  hosts:
    - host: identity-api.com
      paths: ["/"]