version: "3.8"
services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=P@ssw0rd
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "${DATABASE_PORT}:5432"
    networks:
      - backend

  identity-api:
    image: identity-api
    build:
      context: ../../src
      dockerfile: Identity.API/Dockerfile
    depends_on:
      - postgres
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings:DefaultConnection=Server=postgres;Port=5432;Database=identity-api;User Id=postgres;Password=P@ssw0rd;
      - Client:Swagger:Uri:0=${EXTERNAL_HOST_IP}:${CATALOG_API_PORT}
      - Client:React:Uri=${EXTERNAL_HOST_IP}:${REACT_WEB_PORT}
    ports:
      - "${IDENTITY_API_PORT}:80"
    networks:
      - backend
      - frontend

  catalog-api:
    image: catalog-api
    build:
      context: ../../src
      dockerfile: Catalog.API/Dockerfile
    depends_on:
      - postgres
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings:DefaultConnection=Server=postgres;Port=5432;Database=catalog-api;User Id=postgres;Password=P@ssw0rd;
      - Identity:Uri=${EXTERNAL_HOST_IP}:${IDENTITY_API_PORT}
    ports:
      - "${CATALOG_API_PORT}:80"
    networks:
      - backend
      - frontend

  react-web:
    image: react-web
    build:
      context: ../../src
      dockerfile: React.Web/Dockerfile
      args:
        - REACT_APP_IDENTITY_URI=${EXTERNAL_HOST_IP}:${IDENTITY_API_PORT}
        - REACT_APP_CATALOG_URI=${EXTERNAL_HOST_IP}:${CATALOG_API_PORT}
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "${REACT_WEB_PORT}:80"
    networks:
      - frontend

volumes:
  postgres-data:

networks:
  frontend:
  backend: