version: "3"
services:
  sqldb:
    image: mcr.microsoft.com/mssql/server:2017-latest
    environment:
      - SA_PASSWORD=P@ssw0rd
      - ACCEPT_EULA=Y
    volumes:
      - sqldb-data:/var/opt/mssql
    ports:
      - "${SQL_DATABASE_PORT}:1443"
    networks:
      - backend

  identity-api:
    image: identity-api
    build:
      context: ../../src
      dockerfile: Identity.API/Dockerfile
    depends_on:
      - sqldb
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings:DefaultConnection=Server=sqldb,1433;Database=identity-api;User Id=sa;Password=P@ssw0rd;
      - Client:Swagger:Uri=http://${EXTERNAL_HOST_IP}:${BSHOP_API_PORT}
      - Client:React:Uri=http://${EXTERNAL_HOST_IP}:${REACT_WEB_PORT}
    ports:
      - "${IDENTITY_API_PORT}:80"
    networks:
      - backend
      - frontend

  bshop-api:
    image: bshop-api
    build:
      context: ../../src
      dockerfile: BShop.API/Dockerfile
    depends_on:
      - sqldb
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings:DefaultConnection=Server=sqldb,1433;Database=bshop-api;User Id=sa;Password=P@ssw0rd;
      - Identity:Uri=http://${EXTERNAL_HOST_IP}:${IDENTITY_API_PORT}
    ports:
      - "${BSHOP_API_PORT}:80"
    networks:
      - backend
      - frontend

volumes:
  sqldb-data:

networks:
  frontend:
  backend: