version: "3"
services:
  sqldb:
    image: mcr.microsoft.com/mssql/server:2017-latest
    environment:
      - SA_PASSWORD=P@ssw0rd
      - ACCEPT_EULA=Y
    volumes:
      - sqldb-data:/var/opt/mssql
    ports:
      - "${SQL_DATABASE_PORT}:1443"
    networks:
      - backend

  identity-api:
    image: identity-api
    build:
      context: ../../src
      dockerfile: Identity.API/Dockerfile
    depends_on:
      - sqldb
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings:DefaultConnection=Server=sqldb,1433;Database=identity-api;User Id=sa;Password=P@ssw0rd;
      - Client:Swagger:Uri:0=${EXTERNAL_HOST_IP}:${CATALOG_API_PORT}
      - Client:React:Uri=${EXTERNAL_HOST_IP}:${REACT_WEB_PORT}
    ports:
      - "${IDENTITY_API_PORT}:80"
    networks:
      - backend
      - frontend

  catalog-api:
    image: catalog-api
    build:
      context: ../../src
      dockerfile: Catalog.API/Dockerfile
    depends_on:
      - sqldb
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings:DefaultConnection=Server=sqldb,1433;Database=catalog-api;User Id=sa;Password=P@ssw0rd;
      - Identity:Uri=${EXTERNAL_HOST_IP}:${IDENTITY_API_PORT}
    ports:
      - "${CATALOG_API_PORT}:80"
    networks:
      - backend
      - frontend

  react-web:
    image: react-web
    build:
      context: ../../src
      dockerfile: React.Web/Dockerfile
      args:
        - REACT_APP_IDENTITY_URI=${EXTERNAL_HOST_IP}:${IDENTITY_API_PORT}
        - REACT_APP_CATALOG_URI=${EXTERNAL_HOST_IP}:${CATALOG_API_PORT}
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "${REACT_WEB_PORT}:80"
    networks:
      - frontend

volumes:
  sqldb-data:

networks:
  frontend:
  backend: