name: Run dotnet test
description: Run dotnet test

inputs:
  project-path:
    required: true
    description: Project path
  configuration:
    required: false
    default: Release
    description: Build configuration

runs:
  using: composite
  steps:
    - name: Run Tests
      working-directory: ${{inputs.project-path}}
      shell: bash
      run: dotnet test -c ${{inputs.configuration}} /p:CollectCoverage=true
