# Default values for catalog-api.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# helm package .
# helm lint -f ./values.yaml .
# helm upgrade catalog-api --install -f ./values.yaml --namespace=bshop .

replicaCount: 1

image:
  repository: catalog-api
  tag: latest
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: catalog-api
fullnameOverride: catalog-api

env:
  ASPNETCORE_ENVIRONMENT: Production
  ASPNETCORE_URLS: http://0.0.0.0:80
  PathBase: /catalog
  ConnectionStrings__DefaultConnection: Server=postgres-postgresql.infra.svc.cluster.local;Port=5432;Database=catalog-api;User Id=postgres;Password=P@ssw0rd;
  Identity__Uri: http://identity-api

service:
  type: ClusterIP
  port: 80

virtualService:
  enabled: false
  gateway:
    name: default/internal-gateway
    host: k8s.local.com

ingress:
  enabled: false
  annotations:
    kubernetes.io/ingress.class: nginx
  hosts:
    - host: k8s.local.com
      paths: ["/catalog"]

resources:
  limits:
    cpu: 100m
    memory: 256Mi
  requests:
    cpu: 50m
    memory: 128Mi

probes:
  liveness:
    path: /health/liveness
    initialDelaySeconds: 15
    periodSeconds: 30
  readiness:
    path: /health/readiness
    initialDelaySeconds: 30
    periodSeconds: 60
    timeoutSeconds: 5

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
