# helm upgrade catalog-api --install -f ./values.yaml -f values.local.yml --namespace=bshop .

image:
  repository: catalog-api
  tag: latest

env:
  Identity__Uri: http://localhost/identity

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
  hosts:
    - host: localhost
      paths: ["/catalog"]
