apiVersion: v1
kind: ServiceAccount
metadata:
  name: web
  labels:
    app: web
    app.kubernetes.io/name: web
    app.kubernetes.io/component: frontend
    app.kubernetes.io/part-of: micro-commerce
automountServiceAccountToken: false
