apiVersion: v1
kind: Service
metadata:
  name: web
  labels:
    app: web
    app.kubernetes.io/name: web
    app.kubernetes.io/component: frontend
    app.kubernetes.io/part-of: micro-commerce
spec:
  selector:
    app: web
  ports:
  - port: 3000
    targetPort: 3000
    protocol: TCP
