apiVersion: v1
kind: Namespace
metadata:
  name: kubeapps
---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: kubeapps
  namespace: kubeapps
spec:
  interval: 10m
  chart:
    spec:
      chart: kubeapps
      sourceRef:
        kind: HelmRepository
        name: flux-system