name: catalog-api

on:
  push:
    branches: [ master, feature/** ]
    paths: [ src/**, tests/**, .github/**, k8s/** ]
  pull_request:
    branches: [ master ]

env:
  SERVICE_NAME: Catalog.API

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: src/${{env.SERVICE_NAME}}
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Prepare
      run: ls -la
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore -c Release
    - name: Upload result for job test
      uses: actions/upload-artifact@v2
      with:
        name: repo
        path: |
          .

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Download result
      uses: actions/download-artifact@v2
      with:
        name: repo
    - name: Prepare
      run: ls -la
    - name: Run UnitTests
      working-directory: ${{env.SERVICE_NAME}}.UnitTests
      run: dotnet test -c Release /p:CollectCoverage=true
    - name: Run FunctionalTests
      working-directory: ${{env.SERVICE_NAME}}.FunctionalTests
      run: dotnet test -c Release /p:CollectCoverage=true
