name: catalog-api

on:
  workflow_dispatch:
  push:
    branches: [ master, develop, feature/** ]
    paths:
    - src/Services/Catalog/**
    - deploy/k8s/catalog-api
    - pipeline/azure/catalog-api
    - .github/workflows/catalog-api.yml
  pull_request:
    branches: [ master, develop ]
  release:
    types: [ published ]

env:
  PROJECT_PATH: ./src/Services/Catalog/MicroCommerce.Catalog.API

  CONTAINER_REGISTRY: ghcr.io
  IMAGE_NAME: microcommerce-catalog-api

jobs:
  build:
    name: Build and run unit tests
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - uses: ./.github/actions/build-test-dotnet
      with:
        project-path: ${{env.PROJECT_PATH}}

  build_and_push_image:
    name: Build and Push image to registry
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Container Registry ${{env.CONTAINER_REGISTRY}}
      uses: docker/login-action@v1
      with:
        registry: ${{env.CONTAINER_REGISTRY}}
        username: ${{github.repository_owner}}
        password: ${{secrets.PAT_GITHUB_PACKAGE}}

    - name: Build and Push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        push: true
        context: ./src
        file: ${{env.PROJECT_PATH}}/Dockerfile
        tags: ${{env.CONTAINER_REGISTRY}}/${{github.repository_owner}}/${{env.IMAGE_NAME}}:latest
