name: catalog-api

on:
  workflow_dispatch:
  push:
    branches: [ master, develop, feature/** ]
    paths:
    - src/Services/Catalog/**
    - deploy/k8s/catalog-api
    - pipeline/azure/catalog-api
    - .github/workflows/catalog-api.yml
  pull_request:
    branches: [ master, develop ]
  release:
    types: [ published ]

env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true

  DOTNET_VERSION: 5.0.100
  CONFIGURATION: Release

  PROJECT_LOCATION: ./src/Services/Catalog/MicroCommerce.Catalog.API

  CONTAINER_REGISTRY: ghcr.io

jobs:
  build:
    name: Build and run unit tests
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup .NET Core ${{env.DOTNET_VERSION}}
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{env.DOTNET_VERSION}}

    - name: Install dependencies
      working-directory: ${{env.PROJECT_LOCATION}}
      run: dotnet restore

    - name: Build
      working-directory: ${{env.PROJECT_LOCATION}}
      run: dotnet build --no-restore -c ${{env.CONFIGURATION}}

    - name: Run Tests
      working-directory: ${{env.PROJECT_LOCATION}}.Tests
      run: dotnet test -c ${{env.CONFIGURATION}} /p:CollectCoverage=true

  build_and_test_image:
    name: Test image
    runs-on: ubuntu-latest
    needs: build
    services:
      registry:
        image: registry:2
        ports:
          - 5000:5000
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
      with:
        driver-opts: network=host

    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: ./src
        push: true
        file: ${{env.PROJECT_LOCATION}}/Dockerfile
        tags: localhost:5000/app:latest

  build_and_push_image:
    name: Build and push image to registry
    runs-on: ubuntu-latest
    needs: test_image
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Container Registry ${{env.CONTAINER_REGISTRY}}
      uses: docker/login-action@v1
      with:
        registry: ${{env.CONTAINER_REGISTRY}}
        username: ${{ github.repository_owner }}
        password: ${{ secrets.CR_PAT }}

    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        push: true
        context: ./src
        file: ${{env.PROJECT_LOCATION}}/Dockerfile
        tags: micro-commerce/catalog:latest

    - name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}

