name: catalog-api

on:
  push:
    branches: [ master, feature/** ]
    paths: [ src/**, tests/**, .github/**, k8s/** ]
  pull_request:
    branches: [ master ]

env:
  SERVICE_NAME: Catalog.API

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Install dependencies
      working-directory: src/$SERVICE_NAME
      run: dotnet restore
    - name: Build
      working-directory: src/$SERVICE_NAME
      run: dotnet build --no-restore -c Release
    - name: Run UnitTests
      working-directory: tests/$SERVICE_NAME
      run: dotnet test ${SERVICE_NAME}.UnitTests -c Release /p:CollectCoverage=true
    - name: Run FunctionalTests
      working-directory: tests/$SERVICE_NAME
      run: dotnet test ${SERVICE_NAME}.FunctionalTests -c Release /p:CollectCoverage=true
