name: identity-api

on:
  workflow_dispatch:
  push:
    branches: [ master, develop, feature/** ]
    paths:
    - src/Services/Identity/**
    - deploy/k8s/identity-api
    - pipeline/azure/identity-api
    - .github/workflows/identity-api.yml
  pull_request:
    branches: [ master, develop ]
  release:
    types: [ published ]

env:
  DOTNET_VERSION: 5.0.100

  PROJECT_PATH: ./src/Services/Identity/MicroCommerce.Identity.API

  CONTAINER_REGISTRY: ghcr.io
  IMAGE_NAME: microcommerce-identity-api

jobs:
  build:
    name: Build and run unit tests
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{env.DOTNET_VERSION}}

    - uses: ./.github/actions/build-dotnet
      with:
        project-path: ${{env.PROJECT_PATH}}

    - name: Run Tests
      working-directory: ${{env.PROJECT_PATH}}.Tests
      shell: bash
      run: dotnet test -c Release /p:CollectCoverage=true

  build_and_push_image:
    name: Build and Push image to registry
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Container Registry ${{env.CONTAINER_REGISTRY}}
      uses: docker/login-action@v1
      with:
        registry: ${{env.CONTAINER_REGISTRY}}
        username: ${{github.repository_owner}}
        password: ${{secrets.PAT_GITHUB_PACKAGE}}

    - name: Build and Push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        push: true
        context: ./src
        file: ${{env.PROJECT_PATH}}/Dockerfile
        tags: ${{env.CONTAINER_REGISTRY}}/${{github.repository_owner}}/${{env.IMAGE_NAME}}:latest
