name: Release

on:
  workflow_dispatch:
  push:
    tags:
      - "v*.*.*"

env:
  CONTAINER_REGISTRY: ghcr.io

jobs:
  # tests:
  #   uses: ./.github/workflows/dotnet-test.yml
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure 1Password Service Account
        uses: 1password/load-secrets-action/configure@v2
        with:
          service-account-token: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}

      - name: Load Credentials
        id: load-credentials
        uses: 1password/load-secrets-action@v2
        with:
          export-env: false
        env:
          REGISTRY_USERNAME: op://cicd/image-registry/username
          REGISTRY_TOKEN: op://cicd/image-registry/password
          NUGET_TOKEN: op://cicd/nuget/password

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Generate build version
        id: generate-build-version
        run: |
          year=$(date '+%Y')
          month=$(date '+%-m')
          day=$(date '+%d')
          hour=$(date '+%-H%M')
          NEW_VERSION="${year}.${month}${day}.${hour}"
          echo "New Version: $NEW_VERSION"
          echo "NEW_VERSION=$NEW_VERSION" >> $GITHUB_ENV

      - name: Build and Push BuildingBlocks.Common Nuget packages
        working-directory: code/src/BuildingBlocks/BuildingBlocks.Common
        run: |
          dotnet pack -c Release -o . /p:Version=${{ env.NEW_VERSION }}
          dotnet nuget push *.nupkg --api-key ${{ steps.load-credentials.outputs.NUGET_TOKEN }} --source https://nuget.pkg.github.com/${{ github.actor }}/index.json

      - name: Build and Push BuildingBlocks.ServiceDefaults Nuget packages
        working-directory: code/src/BuildingBlocks/BuildingBlocks.ServiceDefaults
        run: |
          dotnet pack -c Release -o . /p:Version=${{ env.NEW_VERSION }}
          dotnet nuget push *.nupkg --api-key ${{ steps.load-credentials.outputs.NUGET_TOKEN }} --source https://nuget.pkg.github.com/${{ github.actor }}/index.json

      - name: Log in to Image Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.CONTAINER_REGISTRY }}
          username: ${{ steps.load-credentials.outputs.REGISTRY_USERNAME }}
          password: ${{ steps.load-credentials.outputs.REGISTRY_TOKEN }}

      - name: Build and Push CartService docker image
        working-directory: code/src/CartService/CartService.Api
        run: |
          dotnet publish -c Release \
            /t:PublishContainer \
            -p ContainerRegistry=${{ env.CONTAINER_REGISTRY }} \
            -p ContainerRepository=${{ github.repository }}/cart-service \
            -p ContainerImageTag=${{ github.ref_name }}

      - name: Build and Push Yarp docker image
        working-directory: code/src/Gateway/Yarp
        run: |
          dotnet publish -c Release \
            /t:PublishContainer \
            -p ContainerRegistry=${{ env.CONTAINER_REGISTRY }} \
            -p ContainerRepository=${{ github.repository }}/yarp \
            -p ContainerImageTag=${{ github.ref_name }}
