name: Release Docker Images

on:
  workflow_dispatch:
  push:
    tags:
      - "v*.*.*"

jobs:
  # tests:
  #   uses: ./.github/workflows/dotnet-test.yml

  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      # Login to GitHub Container Registry
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Build Docker image
      - name: Build Docker image
        working-directory: code/src/CartService/CartService.Api
        run: |
          dotnet publish -c Release \
            /t:PublishContainer \
            -p ContainerRegistry=ghcr.io \
            -p ContainerRepository=${{ github.repository }}/cart-service \
            -p ContainerTag=${{ github.ref_name }}

      # Push Docker image
      - name: Push Docker image
        run: |
          docker push ghcr.io/${{ github.repository }}/cart-service:${{ github.ref_name }}
