name: Release Docker Images

on:
  workflow_dispatch:
  push:
    tags:
      - "v*.*.*"

jobs:
  tests:
    uses: ./.github/workflows/dotnet-test.yml

  release-docker-images:
    needs: [tests]
    env:
      BACKEND_IMAGE_NAME: bao2703/micro-commerce-backend
      FRONTEND_IMAGE_NAME: bao2703/micro-commerce-frontend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Prepare Env
        id: prep
        run: |
          BRANCH=${GITHUB_REF##*/}
          TS=$(date +%s)
          REVISION=${GITHUB_SHA::8}
          BUILD_ID="${BRANCH}-${REVISION}-${TS}"
          LATEST_ID=canary
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            BUILD_ID=${GITHUB_REF/refs\/tags\//}
            LATEST_ID=latest
          fi
          echo BUILD_DATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ') >> $GITHUB_OUTPUT
          echo BUILD_ID=${BUILD_ID} >> $GITHUB_OUTPUT
          echo LATEST_ID=${LATEST_ID} >> $GITHUB_OUTPUT          

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Build and push Backend
        working-directory: ./backend/src/Api
        run: |
          dotnet publish --os linux --arch x64 /t:PublishContainer -c Release -p ContainerImageTags='"${{ steps.prep.outputs.BUILD_ID }};${{ steps.prep.outputs.LATEST_ID }}"' -p ContainerRepository='"${{ env.BACKEND_IMAGE_NAME }}"'
          docker push ${{ env.BACKEND_IMAGE_NAME }}:${{ steps.prep.outputs.BUILD_ID }}
          docker push ${{ env.BACKEND_IMAGE_NAME }}:${{ steps.prep.outputs.LATEST_ID }}

      - name: Build and push Frontend
        uses: docker/build-push-action@v2
        with:
          context: ./frontend
          push: true
          tags: |
            ${{ env.FRONTEND_IMAGE_NAME }}:${{ steps.prep.outputs.BUILD_ID }}
            ${{ env.FRONTEND_IMAGE_NAME }}:${{ steps.prep.outputs.LATEST_ID }}
