trigger:
  branches:
    include:
    - master
    exclude:
    - ref/tags/*
  paths:
    include:
    - pipeline/azure/infrastructure

pool:
  vmImage: ubuntu-latest

variables:
- template: ../variables.yml

jobs:
- job: Install_Mssql
  displayName: Install Mssql linux
  steps:
  - template: ../install-helm-chart-name.yml
    parameters:
      releaseName: mssql
      chartName: stable/mssql-linux
      valueFile: $(Build.SourcesDirectory)/pipeline/k8s/infrastructure/mssql-linux/values.yaml
      namespace: bshop
- job : Install_Nginx
  displayName: Install NginX ingress controller
  steps:
  - template: ../install-helm-chart-name.yml
    parameters:
      releaseName: nginx-ingress
      chartName: stable/nginx-ingress
      valueFile: $(Build.SourcesDirectory)/pipeline/k8s/infrastructure/nginx-ingress/values.yaml
      namespace: default
