trigger:
  branches:
    include:
    - master
    exclude:
    - ref/tags/*
  paths:
    include:
    - pipeline/azure/infrastructure

pool:
  vmImage: ubuntu-latest

variables:
- template: ../variables.yml

jobs:
- job: Deploy_Mssql
  displayName: Deploy Mssql
  steps:
  - template: ../install-helm-chart-name.yml
    parameters:
      releaseName: mssql
      chartName: stable/mssql-linux
      namespace: bshop
