trigger: none

pool:
  vmImage: ubuntu-latest

variables:
- template: ../variables.yml

stages:
- stage: Install_Mssql
  displayName: Install Mssql Linux
  dependsOn: []
  jobs:
  - job: Install_Mssql
    steps:
    - template: ../install-helm-chart-name.yml
      parameters:
        releaseName: mssql
        chartName: stable/mssql-linux
        namespace: bshop
        valueFile: pipeline/k8s/infrastructure/mssql-linux/values.yaml

- stage: Install_Nginx_Ingress
  displayName: Install Nginx ingress controller
  dependsOn: []
  jobs:
  - job : Install_Nginx_Ingress
    steps:
    - template: ../install-helm-chart-name.yml
      parameters:
        releaseName: nginx-ingress
        chartName: stable/nginx-ingress
        namespace: default
        valueFile: pipeline/k8s/infrastructure/nginx-ingress/values.yaml

- stage: Install_SonarQube
  displayName: Install SonarQube
  dependsOn: []
  jobs:
  - job : Install_SonarQube
    steps:
    - template: ../install-helm-chart-name.yml
      parameters:
        releaseName: sonarqube
        chartName: stable/sonarqube
        namespace: default
        valueFile: pipeline/k8s/infrastructure/sonarqube/values.yaml